version: '3.9'

services:
  postgres:
    container_name: course_platform_db
    image: postgres
    environment:
      - POSTGRES_DB=course-platform
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5433:5432